name: Executable Creation

on:
  push:
    branches:    
      - main
      - executable

jobs:
  check-docs:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    # Standard drop-in approach that should work for most people.

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pyinstaller

    - name: Build with pyinstaller
      run: |
        pyinstaller -y executable_entry.spec
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: Executable
        path: dist/ev3sim
